name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # change to 'master' if your default branch is 'master'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload website files
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'  # Use '.' if your index.html is in the root of the repo

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
