name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Use 'master' if that's your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'  # Adjust if your site is in a folder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
